### ISSUE TITLE
V2 Portfolio Changes

### ISSUE THREAD

**Issue by dospore** [tracer-protocol/pools-client#456]
# Task Template

V2 portfolio changes

- [ ] add escrow table
- [ ] change commit signature
- [ ] add claim all button
- [ ] display claimable amounts

Designs: https://www.figma.com/file/Gh6WzO8gLZWDmTvRbw8ikm/Tracer-Style-Guide-%26-Components?node-id=6093%3A242078
