### ISSUE TITLE
Flip Commit Type

### ISSUE THREAD

**Issue by dospore** [tracer-protocol/pools-client#461]
# Task Template

Modal for new flip commit type. 

## Changes from design
- Change auto claim tokens to a disabled input with a coming soon tooltip

## Tasks
- [ ] add flip tab to commit modal
- [ ] add flip breakdown
- [ ] add commit type support to PoolContext Functions

Designs: https://www.figma.com/file/Gh6WzO8gLZWDmTvRbw8ikm/Tracer-Style-Guide-%26-Components?node-id=5427%3A194937
